CREATE TABLE "pais" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "codigo_iso" varchar(3) UNIQUE NOT NULL
);

CREATE TABLE "ciudad" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pais_id" integer NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "departamento_estado" varchar(100)
);

CREATE TABLE "negocio" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "nit_documento" varchar(50),
  "ciudad_id" integer NOT NULL,
  "direccion" varchar(255),
  "telefono" varchar(30),
  "email" varchar(150),
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "sucursal" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "ciudad_id" integer NOT NULL,
  "direccion" varchar(255),
  "telefono" varchar(30),
  "es_principal" boolean NOT NULL DEFAULT true,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "persona" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_documento" varchar(20),
  "numero_documento" varchar(30) UNIQUE,
  "primer_nombre" varchar(100) NOT NULL,
  "segundo_nombre" varchar(100),
  "primer_apellido" varchar(100) NOT NULL,
  "segundo_apellido" varchar(100),
  "telefono" varchar(30),
  "email" varchar(150),
  "ciudad_id" integer,
  "direccion" varchar(255),
  "fecha_nacimiento" date,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" integer UNIQUE NOT NULL,
  "username" varchar(100) UNIQUE,
  "email" varchar(150) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true,
  "ultimo_login" timestamp,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" integer UNIQUE NOT NULL,
  "negocio_id" integer NOT NULL,
  "usuario_id" integer UNIQUE,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "total_gastado" decimal(12,2) NOT NULL DEFAULT 0,
  "fecha_ultima_compra" timestamp,
  "numero_pedidos" integer NOT NULL DEFAULT 0,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "cliente_preferencia" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer NOT NULL,
  "clave" varchar(100) NOT NULL,
  "valor" varchar(255) NOT NULL,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "empleado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" integer UNIQUE NOT NULL,
  "usuario_id" integer UNIQUE NOT NULL,
  "negocio_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "rol_id" integer NOT NULL,
  "fecha_ingreso" date NOT NULL DEFAULT (now()),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer,
  "nombre" varchar(100) NOT NULL,
  "descripcion" varchar(255),
  "es_global" boolean NOT NULL DEFAULT false,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "permiso" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(100) UNIQUE NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "modulo" varchar(100) NOT NULL,
  "descripcion" varchar(255)
);

CREATE TABLE "rol_permiso" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol_id" integer NOT NULL,
  "permiso_id" integer NOT NULL
);

CREATE TABLE "turno_planificado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empleado_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "fecha" date NOT NULL,
  "hora_inicio" time NOT NULL,
  "hora_fin" time NOT NULL,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "asistencia" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empleado_id" integer NOT NULL,
  "turno_planificado_id" integer,
  "check_in" timestamp NOT NULL,
  "check_out" timestamp,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "comision" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empleado_id" integer NOT NULL,
  "tipo" varchar(30) NOT NULL,
  "monto" decimal(10,2) NOT NULL,
  "referencia_id" integer,
  "fecha" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "categoria" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "categoria_padre_id" integer,
  "nombre" varchar(100) NOT NULL,
  "orden" integer NOT NULL DEFAULT 0,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "producto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "categoria_id" integer NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "descripcion" varchar(500),
  "imagen_url" varchar(500),
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "producto_precio" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "precio" decimal(10,2) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "grupo_variante" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" integer NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "obligatorio" boolean NOT NULL DEFAULT true,
  "seleccion_unica" boolean NOT NULL DEFAULT true
);

CREATE TABLE "opcion_variante" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo_variante_id" integer NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "precio_adicional" decimal(10,2) NOT NULL DEFAULT 0,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "adicion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "precio" decimal(10,2) NOT NULL DEFAULT 0,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "producto_adicion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" integer NOT NULL,
  "adicion_id" integer NOT NULL
);

CREATE TABLE "unidad_medida" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "abreviatura" varchar(10) NOT NULL,
  "unidad_base_id" integer,
  "factor_conversion" decimal(12,6)
);

CREATE TABLE "insumo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "unidad_medida_id" integer NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "producto_variante" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" integer NOT NULL,
  "nombre" varchar(150),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "producto_variante_opcion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_variante_id" integer NOT NULL,
  "opcion_variante_id" integer NOT NULL
);

CREATE TABLE "receta_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_variante_id" integer NOT NULL,
  "insumo_id" integer NOT NULL,
  "cantidad" decimal(10,3) NOT NULL,
  "unidad_medida_id" integer NOT NULL
);

CREATE TABLE "inventario_stock" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "insumo_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "cantidad_actual" decimal(12,3) NOT NULL DEFAULT 0,
  "stock_minimo" decimal(12,3) NOT NULL DEFAULT 0,
  "actualizado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "movimiento_inventario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "insumo_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "tipo" varchar(20) NOT NULL,
  "motivo" varchar(50) NOT NULL,
  "cantidad" decimal(12,3) NOT NULL,
  "empleado_id" integer NOT NULL,
  "referencia_id" integer,
  "observacion" varchar(255),
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "proveedor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "nit_documento" varchar(50),
  "telefono" varchar(30),
  "email" varchar(150),
  "direccion" varchar(255),
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "proveedor_insumo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proveedor_id" integer NOT NULL,
  "insumo_id" integer NOT NULL,
  "precio_referencia" decimal(12,2) NOT NULL,
  "unidad_medida_id" integer NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "solicitud_compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "empleado_solicita_id" integer NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'pendiente',
  "motivo" varchar(255),
  "empleado_aprueba_id" integer,
  "fecha_resolucion" timestamp,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "solicitud_compra_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "solicitud_compra_id" integer NOT NULL,
  "insumo_id" integer NOT NULL,
  "cantidad_solicitada" decimal(12,3) NOT NULL,
  "unidad_medida_id" integer NOT NULL
);

CREATE TABLE "orden_compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "solicitud_compra_id" integer NOT NULL,
  "proveedor_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'creada',
  "estado_pago" varchar(20) NOT NULL DEFAULT 'pendiente',
  "total" decimal(12,2) NOT NULL DEFAULT 0,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "orden_compra_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden_compra_id" integer NOT NULL,
  "insumo_id" integer NOT NULL,
  "cantidad_pedida" decimal(12,3) NOT NULL,
  "cantidad_recibida" decimal(12,3) NOT NULL DEFAULT 0,
  "precio_unitario" decimal(12,2) NOT NULL,
  "unidad_medida_id" integer NOT NULL
);

CREATE TABLE "pago_compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden_compra_id" integer NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "metodo" varchar(30) NOT NULL,
  "empleado_id" integer NOT NULL,
  "fecha" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "categoria_gasto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "gasto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "categoria_gasto_id" integer NOT NULL,
  "descripcion" varchar(255) NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "empleado_id" integer NOT NULL,
  "fecha" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "credito_cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer NOT NULL,
  "negocio_id" integer NOT NULL,
  "monto_total" decimal(12,2) NOT NULL,
  "estado_pago" varchar(20) NOT NULL DEFAULT 'pendiente',
  "referencia_id" integer,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "abono_credito_cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "credito_cliente_id" integer NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "metodo" varchar(30) NOT NULL,
  "empleado_id" integer NOT NULL,
  "fecha" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "caja_sesion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sucursal_id" integer NOT NULL,
  "empleado_apertura_id" integer NOT NULL,
  "empleado_cierre_id" integer,
  "monto_base" decimal(12,2) NOT NULL,
  "monto_contado_cierre" decimal(12,2),
  "monto_esperado_cierre" decimal(12,2),
  "diferencia" decimal(12,2),
  "estado" varchar(20) NOT NULL DEFAULT 'abierta',
  "abierta_en" timestamp NOT NULL DEFAULT (now()),
  "cerrada_en" timestamp
);

CREATE TABLE "movimiento_caja" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "caja_sesion_id" integer NOT NULL,
  "tipo" varchar(20) NOT NULL,
  "concepto" varchar(50) NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "metodo" varchar(30) NOT NULL,
  "referencia_id" integer,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "mesa" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sucursal_id" integer NOT NULL,
  "numero" varchar(20) NOT NULL,
  "capacidad" integer NOT NULL DEFAULT 4,
  "estado" varchar(20) NOT NULL DEFAULT 'libre',
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "pedido" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "sucursal_id" integer NOT NULL,
  "canal" varchar(20) NOT NULL,
  "mesa_id" integer,
  "cliente_id" integer,
  "contacto_whatsapp_id" integer,
  "empleado_id" integer NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'abierto',
  "subtotal" decimal(12,2) NOT NULL DEFAULT 0,
  "descuento" decimal(12,2) NOT NULL DEFAULT 0,
  "total" decimal(12,2) NOT NULL DEFAULT 0,
  "creado_en" timestamp NOT NULL DEFAULT (now()),
  "cerrado_en" timestamp
);

CREATE TABLE "pedido_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" integer NOT NULL,
  "producto_variante_id" integer NOT NULL,
  "cantidad" integer NOT NULL DEFAULT 1,
  "precio_unitario" decimal(10,2) NOT NULL,
  "subtotal_item" decimal(12,2) NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'pendiente',
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "pedido_item_adicion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_item_id" integer NOT NULL,
  "adicion_id" integer NOT NULL,
  "precio_aplicado" decimal(10,2) NOT NULL
);

CREATE TABLE "pago_pedido" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" integer NOT NULL,
  "caja_sesion_id" integer NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "metodo" varchar(30) NOT NULL,
  "referencia_comensal" varchar(50),
  "empleado_id" integer NOT NULL,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "estacion_cocina" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sucursal_id" integer NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "orden" integer NOT NULL DEFAULT 0,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "producto_estacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" integer NOT NULL,
  "estacion_cocina_id" integer NOT NULL
);

CREATE TABLE "pedido_item_estacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_item_id" integer NOT NULL,
  "estacion_cocina_id" integer NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'pendiente',
  "entro_en" timestamp NOT NULL DEFAULT (now()),
  "listo_en" timestamp
);

CREATE TABLE "ruta_delivery" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sucursal_id" integer NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "zonas_cubiertas" varchar(500),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "ruta_repartidor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruta_delivery_id" integer NOT NULL,
  "empleado_id" integer NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "salida_reparto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruta_delivery_id" integer NOT NULL,
  "empleado_id" integer NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'preparando',
  "salio_en" timestamp,
  "finalizo_en" timestamp,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "pedido_delivery" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" integer UNIQUE NOT NULL,
  "ruta_delivery_id" integer,
  "salida_reparto_id" integer,
  "direccion_texto" varchar(255) NOT NULL,
  "barrio" varchar(100),
  "latitud" decimal(10,7),
  "longitud" decimal(10,7),
  "estado_entrega" varchar(20) NOT NULL DEFAULT 'pendiente',
  "orden_en_ruta" integer,
  "entregado_en" timestamp
);

CREATE TABLE "anulacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" integer NOT NULL,
  "pedido_item_id" integer,
  "motivo" varchar(255) NOT NULL,
  "requiere_autorizacion" boolean NOT NULL,
  "empleado_solicita_id" integer NOT NULL,
  "empleado_autoriza_id" integer,
  "estado" varchar(20) NOT NULL DEFAULT 'aprobada',
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "comprobante_impresion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" integer NOT NULL,
  "empleado_id" integer NOT NULL,
  "es_reimpresion" boolean NOT NULL DEFAULT false,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "contacto_whatsapp" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "negocio_id" integer NOT NULL,
  "telefono" varchar(30) NOT NULL,
  "nombre" varchar(150),
  "direccion" varchar(255),
  "creado_en" timestamp NOT NULL DEFAULT (now()),
  "actualizado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "conversacion_whatsapp" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contacto_whatsapp_id" integer NOT NULL,
  "negocio_id" integer NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'bot',
  "empleado_id" integer,
  "iniciada_en" timestamp NOT NULL DEFAULT (now()),
  "cerrada_en" timestamp
);

CREATE TABLE "mensaje_whatsapp" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversacion_whatsapp_id" integer NOT NULL,
  "emisor_tipo" varchar(20) NOT NULL,
  "empleado_id" integer,
  "contenido" text NOT NULL,
  "enviado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "cliente_preferencia" ("cliente_id", "clave");

CREATE UNIQUE INDEX ON "rol_permiso" ("rol_id", "permiso_id");

CREATE UNIQUE INDEX ON "producto_precio" ("producto_id", "sucursal_id");

CREATE UNIQUE INDEX ON "producto_adicion" ("producto_id", "adicion_id");

CREATE UNIQUE INDEX ON "producto_variante_opcion" ("producto_variante_id", "opcion_variante_id");

CREATE UNIQUE INDEX ON "receta_item" ("producto_variante_id", "insumo_id");

CREATE UNIQUE INDEX ON "inventario_stock" ("insumo_id", "sucursal_id");

CREATE UNIQUE INDEX ON "proveedor_insumo" ("proveedor_id", "insumo_id");

CREATE UNIQUE INDEX ON "mesa" ("sucursal_id", "numero");

CREATE UNIQUE INDEX ON "producto_estacion" ("producto_id", "estacion_cocina_id");

CREATE UNIQUE INDEX ON "ruta_repartidor" ("ruta_delivery_id", "empleado_id");

CREATE UNIQUE INDEX ON "contacto_whatsapp" ("negocio_id", "telefono");

COMMENT ON TABLE "pais" IS 'Catálogo de países. Reutilizable por toda la app.';

COMMENT ON TABLE "ciudad" IS 'Catálogo de ciudades, ligado a país.';

COMMENT ON TABLE "negocio" IS 'Es el TENANT. Cada negocio es un cliente del sistema, datos aislados.';

COMMENT ON TABLE "sucursal" IS 'Hoy existe 1 fila por negocio, pero el modelo soporta N desde ya. Toda entidad operativa futura referenciará sucursal_id.';

COMMENT ON TABLE "persona" IS 'Datos humanos puros. No sabe nada de login ni de sistema. Una persona puede ser Cliente y/o Empleado a la vez.';

COMMENT ON TABLE "usuario" IS 'Solo lo necesario para login. Si la persona aún no necesita acceso al sistema (ej: cliente sin app), simplemente no tiene fila aquí.';

COMMENT ON TABLE "cliente" IS 'Un Cliente pertenece a un negocio específico. usuario_id es NULL hasta que el cliente necesite loguearse (app, fidelización futura). Los campos de resumen (total_gastado, fecha_ultima_compra, numero_pedidos) son cache calculado — el detalle real vivirá en Pedidos/Ventas cuando se diseñe ese módulo. Se actualizan desde ahí, no se editan a mano.';

COMMENT ON TABLE "cliente_preferencia" IS 'Diseño clave-valor flexible: permite agregar cualquier tipo de preferencia sin alterar el esquema (alergias, gustos, hábitos). clave no tiene catálogo fijo a propósito, para no limitar lo que el negocio puede registrar.';

COMMENT ON TABLE "empleado" IS 'Un Empleado SIEMPRE tiene Usuario (decisión confirmada: todos los roles loguean, incluso cocina/repartidor). Pertenece a un único negocio.';

COMMENT ON TABLE "rol" IS 'Roles base del sistema tienen negocio_id = NULL y es_global = true (admin, cajero, mesero, cocina, repartidor, gerente). Cada negocio puede crear los suyos con negocio_id propio.';

COMMENT ON TABLE "permiso" IS 'Catálogo fijo de acciones del sistema. Definido por el sistema, no por el negocio.';

COMMENT ON TABLE "rol_permiso" IS 'Tabla puente: qué permisos tiene cada rol.';

COMMENT ON TABLE "turno_planificado" IS 'El horario planeado de antemano para un empleado en una fecha específica. No implica que realmente haya trabajado esas horas — eso lo registra Asistencia.';

COMMENT ON TABLE "asistencia" IS 'Lo que realmente pasó: hora real de entrada/salida. Se compara contra turno_planificado para medir puntualidad, pero puede existir sin turno planificado (turno extra no programado).';

COMMENT ON TABLE "comision" IS 'Comisión generada por venta (mesero), propina, o entrega (repartidor). referencia_id queda como puente libre hacia Pedidos/Ventas/Delivery, módulos aún no diseñados.';

COMMENT ON TABLE "categoria" IS 'Jerarquía vía auto-referencia: Comidas > Carnes > Res. categoria_padre_id null = nivel raíz.';

COMMENT ON TABLE "producto" IS 'El producto base, sin precio (el precio vive en producto_precio, por sucursal). Variantes y adiciones se modelan aparte.';

COMMENT ON TABLE "producto_precio" IS 'Mismo producto puede tener precio distinto por sucursal. Hoy con 1 sucursal hay 1 fila por producto, pero el modelo ya soporta N.';

COMMENT ON TABLE "grupo_variante" IS 'Agrupa opciones excluyentes entre sí, ej: "Tamaño" agrupa Pequeño/Grande. Un producto puede tener varios grupos (Tamaño + Tipo de carne).';

COMMENT ON TABLE "opcion_variante" IS 'Una opción dentro de un grupo de variante. precio_adicional puede ser 0 (sin costo extra) o positivo (ej: Grande +$3000).';

COMMENT ON TABLE "adicion" IS 'Catálogo de adiciones a nivel de negocio, reutilizable entre productos (ej: "Queso extra" aplica a varias hamburguesas).';

COMMENT ON TABLE "producto_adicion" IS 'Tabla puente: qué adiciones están disponibles para cada producto. El precio de la adición se toma de adicion.precio (puede sobreescribirse aquí si en el futuro un producto necesita un precio distinto para la misma adición).';

COMMENT ON TABLE "unidad_medida" IS 'Catálogo de unidades. Cada "familia" (peso, volumen, unidad) tiene una unidad base (ej: Gramo para peso). factor_conversion convierte hacia esa base: kg.factor_conversion = 1000 significa 1kg = 1000g.';

COMMENT ON TABLE "insumo" IS 'Versión mínima para que Receta tenga a qué apuntar. Stock, movimientos y alertas de stock bajo se diseñan en el módulo de Inventario.';

COMMENT ON TABLE "producto_variante" IS 'Representa UNA combinación específica de opciones de variante para un producto (ej: Grande + Res). La receta se ancla aquí, no en producto directamente, porque cada combinación consume insumos distinto.';

COMMENT ON TABLE "producto_variante_opcion" IS 'Tabla puente: qué opciones (de qué grupos de variante) componen esta combinación concreta. Ej: producto_variante "Grande-Res" = opcion "Grande" + opcion "Res".';

COMMENT ON TABLE "receta_item" IS 'Cada fila = "esta combinación de producto consume X cantidad de este insumo". unidad_medida_id permite que la receta diga "150 g" aunque el insumo se almacene en kg — la conversión se resuelve con unidad_medida.factor_conversion al descontar inventario.';

COMMENT ON TABLE "inventario_stock" IS 'Cache del stock actual por insumo+sucursal. Es la fuente RÁPIDA de consulta (ej: "¿hay suficiente queso para esta receta?"). Se actualiza a partir de movimiento_inventario, nunca se edita directo a mano — así el número siempre coincide con la suma de su historial.';

COMMENT ON TABLE "movimiento_inventario" IS 'Historial inmutable y fuente de verdad del inventario. cantidad_actual en inventario_stock se recalcula/actualiza a partir de esta tabla. referencia_id queda como puente libre hacia Compras/Pedidos, igual que hicimos en comision.referencia_id.';

COMMENT ON TABLE "proveedor" IS 'Catálogo de proveedores por negocio.';

COMMENT ON TABLE "proveedor_insumo" IS 'Lista de precios del proveedor. precio_referencia es orientativo — el precio real de cada compra se registra en orden_compra_item, porque puede negociarse o cambiar.';

COMMENT ON TABLE "solicitud_compra" IS 'Solicitud inicial, puede originarse manualmente o por alerta de stock bajo (inventario_stock.cantidad_actual < stock_minimo). Requiere aprobación de un rol autorizado antes de generar la Orden de Compra.';

COMMENT ON TABLE "solicitud_compra_item" IS 'Insumos y cantidades pedidas en la solicitud. No incluye proveedor ni precio todavía — eso se decide al generar la Orden de Compra.';

COMMENT ON TABLE "orden_compra" IS 'Se genera solo a partir de una solicitud_compra ya aprobada. estado refleja si ya se recibió la mercancía (parcial o completa) — es independiente de estado_pago, porque puede recibirse en crédito sin haber pagado. estado_pago se recalcula cada vez que se inserta una fila en pago_compra (pendiente: $0 pagado; pago_parcial: 0 < pagado < total; pagada: pagado >= total). No se edita a mano, igual que inventario_stock con sus movimientos.';

COMMENT ON TABLE "orden_compra_item" IS 'cantidad_recibida < cantidad_pedida indica recepción parcial. Cada recepción de mercancía actualiza este campo y genera un movimiento_inventario tipo entrada.';

COMMENT ON TABLE "pago_compra" IS 'Cada abono es una fila independiente. El saldo pendiente de la orden_compra = total - SUM(pago_compra.monto) de sus pagos. Permite crédito con el proveedor vía pagos parciales.';

COMMENT ON TABLE "categoria_gasto" IS 'Catálogo de categorías de gasto por negocio, para poder reportar por categoría.';

COMMENT ON TABLE "gasto" IS 'Gastos operativos que NO son compra de insumos (esos viven en orden_compra). Ej: pago de luz, arriendo, nómina, reparación de equipo.';

COMMENT ON TABLE "credito_cliente" IS 'Una deuda de un cliente con el negocio (fiado). Mismo patrón que orden_compra: estado_pago se recalcula a partir de sus abonos, no se edita a mano.';

COMMENT ON TABLE "abono_credito_cliente" IS 'Cada abono del cliente es una fila independiente, igual que pago_compra. El saldo pendiente = monto_total - SUM(abono_credito_cliente.monto).';

COMMENT ON TABLE "caja_sesion" IS 'Una sesión de caja física por sucursal (por turno o por día, según cómo opere cada negocio). diferencia revela sobrantes/faltantes al momento del cierre. Se conecta con Personal y Turnos: normalmente abre/cierra quien está de turno.';

COMMENT ON TABLE "movimiento_caja" IS 'Cada movimiento de dinero dentro de una sesión de caja. monto_esperado_cierre en caja_sesion se calcula sumando estos movimientos filtrados por metodo=efectivo. Es el historial real, igual patrón que movimiento_inventario.';

COMMENT ON TABLE "mesa" IS 'Mesas del salón por sucursal. estado se actualiza cuando se abre/cierra un pedido tipo "mesa".';

COMMENT ON TABLE "pedido" IS 'Tabla central de toda venta. canal define mesa/llevar/delivery de forma fija. Mientras estado = "abierto" se pueden agregar/quitar pedido_item. Al pagar completo, estado pasa a "pagado" — desde ahí ya no se edita.';

COMMENT ON TABLE "pedido_item" IS 'Cada línea del pedido. Se puede agregar/quitar mientras pedido.estado = "abierto". estado propio permite que Cocina (KDS, módulo futuro) marque item por item, no todo el pedido junto.';

COMMENT ON TABLE "pedido_item_adicion" IS 'Adiciones elegidas para este item específico (ej: este pedido_item de hamburguesa lleva "Queso extra"). precio_aplicado se copia, no se recalcula si el precio de la adición cambia después.';

COMMENT ON TABLE "pago_pedido" IS 'Cada fila es un pago parcial. Un pedido puede tener N filas (split entre métodos o comensales). pedido.estado pasa a "pagado" cuando SUM(pago_pedido.monto) >= pedido.total. Si metodo = "credito_cliente", se genera un credito_cliente en vez de un movimiento_caja inmediato.';

COMMENT ON TABLE "estacion_cocina" IS 'Estaciones de cocina por sucursal. Cada negocio define las suyas (no hay catálogo fijo, porque varía mucho entre restaurantes).';

COMMENT ON TABLE "producto_estacion" IS 'A qué estación pertenece este producto (ej: Hamburguesa → Parrilla). Se hereda automáticamente al pedido_item_estacion cuando se crea el pedido, así cocina no tiene que clasificar manualmente cada vez.';

COMMENT ON TABLE "pedido_item_estacion" IS 'Seguimiento real por estación. Heredado de producto_estacion al crear el pedido_item. Permite medir tiempos por estación (listo_en - entro_en) y que cada estación vea solo lo suyo en su pantalla KDS. Cuando TODAS las filas de un pedido_item quedan en "listo", se actualiza pedido_item.estado a "listo".';

COMMENT ON TABLE "ruta_delivery" IS 'Zona de reparto. MVP: zonas_cubiertas es texto libre con los barrios. Futuro: se reemplaza/complementa por radio de coordenadas + algoritmo de cercanía, sin romper el modelo porque pedido_delivery ya guarda lat/long.';

COMMENT ON TABLE "ruta_repartidor" IS 'Qué repartidores pertenecen a cada ruta. Puede ser uno o varios por ruta, como confirmaste — de ahí se elige el disponible al momento de asignar.';

COMMENT ON TABLE "salida_reparto" IS 'Una "vuelta" de reparto: un repartidor, varios pedidos posibles (confirmado: puede llevar 3 domicilios en una salida). Se elige repartidor disponible de ruta_repartidor para esa ruta.';

COMMENT ON TABLE "pedido_delivery" IS 'Datos específicos de un pedido cuando canal = "delivery". latitud/longitud existen desde el MVP aunque la asignación de ruta hoy se haga por "barrio" en texto — así el futuro algoritmo de cercanía no requiere migración, solo empieza a leer estos campos.';

COMMENT ON TABLE "anulacion" IS 'requiere_autorizacion se calcula al crear la anulación: true si el pedido ya estaba "pagado" (necesita Gerente u otro rol autorizado), false si seguía "abierto" (el mismo empleado puede anular directo, estado queda en "aprobada" automáticamente). pedido_item_id null = anula el pedido completo; con valor = anulación parcial de un solo item.';

COMMENT ON TABLE "comprobante_impresion" IS 'Registro de cada vez que se imprime el comprobante de un pedido. es_reimpresion distingue la original de copias posteriores — útil para detectar reimpresiones sospechosas en auditoría. No almacena el contenido del comprobante (eso se genera al momento desde pedido + pedido_item), solo el registro de que se imprimió.';

COMMENT ON TABLE "contacto_whatsapp" IS 'Contacto ligero por negocio. NO es Persona ni Cliente — solo guarda el último dato dado para no volver a preguntarlo. telefono es único POR NEGOCIO (un mismo número puede escribirle a 2 negocios distintos del sistema).';

COMMENT ON TABLE "conversacion_whatsapp" IS 'Agrupa los mensajes de una sesión de chat. estado controla si responde el LLM o un humano tomó el control. empleado_id se llena solo cuando un humano interviene.';

COMMENT ON TABLE "mensaje_whatsapp" IS 'Cada mensaje individual. emisor_tipo distingue si lo escribió el cliente, el LLM, o un empleado humano que tomó el control. Diseño flexible: no requiere 3 tablas separadas por tipo de emisor.';

ALTER TABLE "ciudad" ADD FOREIGN KEY ("pais_id") REFERENCES "pais" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "negocio" ADD FOREIGN KEY ("ciudad_id") REFERENCES "ciudad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sucursal" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sucursal" ADD FOREIGN KEY ("ciudad_id") REFERENCES "ciudad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("ciudad_id") REFERENCES "ciudad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("id") REFERENCES "usuario" ("persona_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("id") REFERENCES "cliente" ("persona_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cliente" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("id") REFERENCES "cliente" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cliente_preferencia" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("id") REFERENCES "empleado" ("persona_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("id") REFERENCES "empleado" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "empleado" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "empleado" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "empleado" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rol" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rol_permiso" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rol_permiso" ADD FOREIGN KEY ("permiso_id") REFERENCES "permiso" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno_planificado" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno_planificado" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("turno_planificado_id") REFERENCES "turno_planificado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comision" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categoria" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categoria" ADD FOREIGN KEY ("categoria_padre_id") REFERENCES "categoria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto" ADD FOREIGN KEY ("categoria_id") REFERENCES "categoria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_precio" ADD FOREIGN KEY ("producto_id") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_precio" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "grupo_variante" ADD FOREIGN KEY ("producto_id") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "opcion_variante" ADD FOREIGN KEY ("grupo_variante_id") REFERENCES "grupo_variante" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "adicion" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_adicion" ADD FOREIGN KEY ("producto_id") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_adicion" ADD FOREIGN KEY ("adicion_id") REFERENCES "adicion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "unidad_medida" ADD FOREIGN KEY ("unidad_base_id") REFERENCES "unidad_medida" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "insumo" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "insumo" ADD FOREIGN KEY ("unidad_medida_id") REFERENCES "unidad_medida" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_variante" ADD FOREIGN KEY ("producto_id") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_variante_opcion" ADD FOREIGN KEY ("producto_variante_id") REFERENCES "producto_variante" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_variante_opcion" ADD FOREIGN KEY ("opcion_variante_id") REFERENCES "opcion_variante" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receta_item" ADD FOREIGN KEY ("producto_variante_id") REFERENCES "producto_variante" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receta_item" ADD FOREIGN KEY ("insumo_id") REFERENCES "insumo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receta_item" ADD FOREIGN KEY ("unidad_medida_id") REFERENCES "unidad_medida" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventario_stock" ADD FOREIGN KEY ("insumo_id") REFERENCES "insumo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventario_stock" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimiento_inventario" ADD FOREIGN KEY ("insumo_id") REFERENCES "insumo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimiento_inventario" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimiento_inventario" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proveedor" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proveedor_insumo" ADD FOREIGN KEY ("proveedor_id") REFERENCES "proveedor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proveedor_insumo" ADD FOREIGN KEY ("insumo_id") REFERENCES "insumo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proveedor_insumo" ADD FOREIGN KEY ("unidad_medida_id") REFERENCES "unidad_medida" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitud_compra" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitud_compra" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitud_compra" ADD FOREIGN KEY ("empleado_solicita_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitud_compra" ADD FOREIGN KEY ("empleado_aprueba_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitud_compra_item" ADD FOREIGN KEY ("solicitud_compra_id") REFERENCES "solicitud_compra" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitud_compra_item" ADD FOREIGN KEY ("insumo_id") REFERENCES "insumo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solicitud_compra_item" ADD FOREIGN KEY ("unidad_medida_id") REFERENCES "unidad_medida" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_compra" ADD FOREIGN KEY ("solicitud_compra_id") REFERENCES "solicitud_compra" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_compra" ADD FOREIGN KEY ("proveedor_id") REFERENCES "proveedor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_compra" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_compra_item" ADD FOREIGN KEY ("orden_compra_id") REFERENCES "orden_compra" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_compra_item" ADD FOREIGN KEY ("insumo_id") REFERENCES "insumo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_compra_item" ADD FOREIGN KEY ("unidad_medida_id") REFERENCES "unidad_medida" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pago_compra" ADD FOREIGN KEY ("orden_compra_id") REFERENCES "orden_compra" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pago_compra" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categoria_gasto" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gasto" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gasto" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gasto" ADD FOREIGN KEY ("categoria_gasto_id") REFERENCES "categoria_gasto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gasto" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credito_cliente" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credito_cliente" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "abono_credito_cliente" ADD FOREIGN KEY ("credito_cliente_id") REFERENCES "credito_cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "abono_credito_cliente" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "caja_sesion" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "caja_sesion" ADD FOREIGN KEY ("empleado_apertura_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "caja_sesion" ADD FOREIGN KEY ("empleado_cierre_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimiento_caja" ADD FOREIGN KEY ("caja_sesion_id") REFERENCES "caja_sesion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mesa" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido" ADD FOREIGN KEY ("mesa_id") REFERENCES "mesa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido" ADD FOREIGN KEY ("contacto_whatsapp_id") REFERENCES "contacto_whatsapp" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_item" ADD FOREIGN KEY ("pedido_id") REFERENCES "pedido" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_item" ADD FOREIGN KEY ("producto_variante_id") REFERENCES "producto_variante" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_item_adicion" ADD FOREIGN KEY ("pedido_item_id") REFERENCES "pedido_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_item_adicion" ADD FOREIGN KEY ("adicion_id") REFERENCES "adicion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pago_pedido" ADD FOREIGN KEY ("pedido_id") REFERENCES "pedido" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pago_pedido" ADD FOREIGN KEY ("caja_sesion_id") REFERENCES "caja_sesion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pago_pedido" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estacion_cocina" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_estacion" ADD FOREIGN KEY ("producto_id") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto_estacion" ADD FOREIGN KEY ("estacion_cocina_id") REFERENCES "estacion_cocina" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_item_estacion" ADD FOREIGN KEY ("pedido_item_id") REFERENCES "pedido_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_item_estacion" ADD FOREIGN KEY ("estacion_cocina_id") REFERENCES "estacion_cocina" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ruta_delivery" ADD FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ruta_repartidor" ADD FOREIGN KEY ("ruta_delivery_id") REFERENCES "ruta_delivery" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ruta_repartidor" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "salida_reparto" ADD FOREIGN KEY ("ruta_delivery_id") REFERENCES "ruta_delivery" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "salida_reparto" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido" ADD FOREIGN KEY ("id") REFERENCES "pedido_delivery" ("pedido_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_delivery" ADD FOREIGN KEY ("ruta_delivery_id") REFERENCES "ruta_delivery" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_delivery" ADD FOREIGN KEY ("salida_reparto_id") REFERENCES "salida_reparto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anulacion" ADD FOREIGN KEY ("pedido_id") REFERENCES "pedido" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anulacion" ADD FOREIGN KEY ("pedido_item_id") REFERENCES "pedido_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anulacion" ADD FOREIGN KEY ("empleado_solicita_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anulacion" ADD FOREIGN KEY ("empleado_autoriza_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comprobante_impresion" ADD FOREIGN KEY ("pedido_id") REFERENCES "pedido" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comprobante_impresion" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contacto_whatsapp" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversacion_whatsapp" ADD FOREIGN KEY ("contacto_whatsapp_id") REFERENCES "contacto_whatsapp" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversacion_whatsapp" ADD FOREIGN KEY ("negocio_id") REFERENCES "negocio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversacion_whatsapp" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensaje_whatsapp" ADD FOREIGN KEY ("conversacion_whatsapp_id") REFERENCES "conversacion_whatsapp" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensaje_whatsapp" ADD FOREIGN KEY ("empleado_id") REFERENCES "empleado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
