"""complete restaurant schema

Revision ID: e13f7527181f
Revises: 0001_initial
Create Date: 2026-06-22 20:48:30.580482

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002_complete_schema'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('units_of_measure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('base_unit_id', sa.Uuid(), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('second_last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_index(op.f('ix_persons_city_id'), 'persons', ['city_id'], unique=False)
    op.create_table('addons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addons_tenant_id'), 'addons', ['tenant_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_parent_category_id'), 'categories', ['parent_category_id'], unique=False)
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_tenant_id'), 'expense_categories', ['tenant_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_tenant_id'), 'ingredients', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ingredients_unit_of_measure_id'), 'ingredients', ['unit_of_measure_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('whatsapp_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_whatsapp_contacts_tenant_phone')
    )
    op.create_index(op.f('ix_whatsapp_contacts_tenant_id'), 'whatsapp_contacts', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_person_id'), 'customers', ['person_id'], unique=True)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.create_table('delivery_routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('covered_zones', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_routes_branch_id'), 'delivery_routes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_delivery_routes_tenant_id'), 'delivery_routes', ['tenant_id'], unique=False)
    op.create_table('dining_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'number', name='uq_dining_tables_branch_number')
    )
    op.create_index(op.f('ix_dining_tables_branch_id'), 'dining_tables', ['branch_id'], unique=False)
    op.create_index(op.f('ix_dining_tables_tenant_id'), 'dining_tables', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('hired_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employees_person_id'), 'employees', ['person_id'], unique=True)
    op.create_index(op.f('ix_employees_role_id'), 'employees', ['role_id'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('inventory_stocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'branch_id', name='uq_inventory_stocks_ingredient_branch')
    )
    op.create_index(op.f('ix_inventory_stocks_branch_id'), 'inventory_stocks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_stocks_ingredient_id'), 'inventory_stocks', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_inventory_stocks_tenant_id'), 'inventory_stocks', ['tenant_id'], unique=False)
    op.create_table('kitchen_stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_stations_branch_id'), 'kitchen_stations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_kitchen_stations_tenant_id'), 'kitchen_stations', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('supplier_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'ingredient_id', name='uq_supplier_ingredients_supplier_ingredient')
    )
    op.create_index(op.f('ix_supplier_ingredients_ingredient_id'), 'supplier_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_supplier_ingredients_supplier_id'), 'supplier_ingredients', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_ingredients_tenant_id'), 'supplier_ingredients', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_supplier_ingredients_unit_of_measure_id'), 'supplier_ingredients', ['unit_of_measure_id'], unique=False)
    op.create_table('cash_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opened_by_employee_id', sa.Uuid(), nullable=False),
    sa.Column('closed_by_employee_id', sa.Uuid(), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_branch_id'), 'cash_sessions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_closed_by_employee_id'), 'cash_sessions', ['closed_by_employee_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_opened_by_employee_id'), 'cash_sessions', ['opened_by_employee_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_tenant_id'), 'cash_sessions', ['tenant_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_employee_id'), 'commissions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_commissions_tenant_id'), 'commissions', ['tenant_id'], unique=False)
    op.create_table('customer_credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_credits_customer_id'), 'customer_credits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_credits_tenant_id'), 'customer_credits', ['tenant_id'], unique=False)
    op.create_table('customer_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_preferences_customer_id'), 'customer_preferences', ['customer_id'], unique=False)
    op.create_index('ix_customer_preferences_customer_key', 'customer_preferences', ['customer_id', 'key'], unique=False)
    op.create_index(op.f('ix_customer_preferences_tenant_id'), 'customer_preferences', ['tenant_id'], unique=False)
    op.create_table('delivery_route_drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_route_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_route_id'], ['delivery_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_route_id', 'employee_id', name='uq_delivery_route_drivers_route_employee')
    )
    op.create_index(op.f('ix_delivery_route_drivers_delivery_route_id'), 'delivery_route_drivers', ['delivery_route_id'], unique=False)
    op.create_index(op.f('ix_delivery_route_drivers_employee_id'), 'delivery_route_drivers', ['employee_id'], unique=False)
    op.create_index(op.f('ix_delivery_route_drivers_tenant_id'), 'delivery_route_drivers', ['tenant_id'], unique=False)
    op.create_table('delivery_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_route_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_route_id'], ['delivery_routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_runs_delivery_route_id'), 'delivery_runs', ['delivery_route_id'], unique=False)
    op.create_index(op.f('ix_delivery_runs_employee_id'), 'delivery_runs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_delivery_runs_tenant_id'), 'delivery_runs', ['tenant_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expense_category_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('incurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_branch_id'), 'expenses', ['branch_id'], unique=False)
    op.create_index(op.f('ix_expenses_employee_id'), 'expenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_category_id'), 'expenses', ['expense_category_id'], unique=False)
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_branch_id'), 'inventory_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_employee_id'), 'inventory_movements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_ingredient_id'), 'inventory_movements', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_tenant_id'), 'inventory_movements', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('dining_table_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('whatsapp_contact_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dining_table_id'], ['dining_tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_contact_id'], ['whatsapp_contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_branch_id'), 'orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_dining_table_id'), 'orders', ['dining_table_id'], unique=False)
    op.create_index(op.f('ix_orders_employee_id'), 'orders', ['employee_id'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_orders_whatsapp_contact_id'), 'orders', ['whatsapp_contact_id'], unique=False)
    op.create_table('planned_shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_shifts_branch_id'), 'planned_shifts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_planned_shifts_employee_id'), 'planned_shifts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_planned_shifts_tenant_id'), 'planned_shifts', ['tenant_id'], unique=False)
    op.create_table('product_addons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('addon_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'addon_id', name='uq_product_addons_product_addon')
    )
    op.create_index(op.f('ix_product_addons_addon_id'), 'product_addons', ['addon_id'], unique=False)
    op.create_index(op.f('ix_product_addons_product_id'), 'product_addons', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_addons_tenant_id'), 'product_addons', ['tenant_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'branch_id', name='uq_product_prices_product_branch')
    )
    op.create_index(op.f('ix_product_prices_branch_id'), 'product_prices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_prices_tenant_id'), 'product_prices', ['tenant_id'], unique=False)
    op.create_table('product_stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('kitchen_station_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['kitchen_station_id'], ['kitchen_stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'kitchen_station_id', name='uq_product_stations_product_station')
    )
    op.create_index(op.f('ix_product_stations_kitchen_station_id'), 'product_stations', ['kitchen_station_id'], unique=False)
    op.create_index(op.f('ix_product_stations_product_id'), 'product_stations', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_stations_tenant_id'), 'product_stations', ['tenant_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_tenant_id'), 'product_variants', ['tenant_id'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_employee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('approved_by_employee_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requests_approved_by_employee_id'), 'purchase_requests', ['approved_by_employee_id'], unique=False)
    op.create_index(op.f('ix_purchase_requests_branch_id'), 'purchase_requests', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchase_requests_requested_by_employee_id'), 'purchase_requests', ['requested_by_employee_id'], unique=False)
    op.create_index(op.f('ix_purchase_requests_tenant_id'), 'purchase_requests', ['tenant_id'], unique=False)
    op.create_table('variant_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('single_selection', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_groups_product_id'), 'variant_groups', ['product_id'], unique=False)
    op.create_index(op.f('ix_variant_groups_tenant_id'), 'variant_groups', ['tenant_id'], unique=False)
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('whatsapp_contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_contact_id'], ['whatsapp_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_conversations_employee_id'), 'whatsapp_conversations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_tenant_id'), 'whatsapp_conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_whatsapp_contact_id'), 'whatsapp_conversations', ['whatsapp_contact_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('planned_shift_id', sa.Uuid(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planned_shift_id'], ['planned_shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_employee_id'), 'attendances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendances_planned_shift_id'), 'attendances', ['planned_shift_id'], unique=False)
    op.create_index(op.f('ix_attendances_tenant_id'), 'attendances', ['tenant_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cash_session_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('concept', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_branch_id'), 'cash_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_cash_session_id'), 'cash_movements', ['cash_session_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_tenant_id'), 'cash_movements', ['tenant_id'], unique=False)
    op.create_table('customer_credit_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_credit_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_credit_id'], ['customer_credits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_credit_payments_customer_credit_id'), 'customer_credit_payments', ['customer_credit_id'], unique=False)
    op.create_index(op.f('ix_customer_credit_payments_employee_id'), 'customer_credit_payments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_customer_credit_payments_tenant_id'), 'customer_credit_payments', ['tenant_id'], unique=False)
    op.create_table('order_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_route_id', sa.Uuid(), nullable=True),
    sa.Column('delivery_run_id', sa.Uuid(), nullable=True),
    sa.Column('address_text', sa.String(length=255), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('route_position', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_route_id'], ['delivery_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_run_id'], ['delivery_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_deliveries_delivery_route_id'), 'order_deliveries', ['delivery_route_id'], unique=False)
    op.create_index(op.f('ix_order_deliveries_delivery_run_id'), 'order_deliveries', ['delivery_run_id'], unique=False)
    op.create_index(op.f('ix_order_deliveries_order_id'), 'order_deliveries', ['order_id'], unique=True)
    op.create_index(op.f('ix_order_deliveries_tenant_id'), 'order_deliveries', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_branch_id'), 'order_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_variant_id'), 'order_items', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_order_items_tenant_id'), 'order_items', ['tenant_id'], unique=False)
    op.create_table('order_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('cash_session_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('diner_reference', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_payments_branch_id'), 'order_payments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_order_payments_cash_session_id'), 'order_payments', ['cash_session_id'], unique=False)
    op.create_index(op.f('ix_order_payments_employee_id'), 'order_payments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_order_payments_order_id'), 'order_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_payments_tenant_id'), 'order_payments', ['tenant_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_request_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_branch_id'), 'purchase_orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_purchase_request_id'), 'purchase_orders', ['purchase_request_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_table('purchase_request_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_request_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_request_items_ingredient_id'), 'purchase_request_items', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_purchase_request_items_purchase_request_id'), 'purchase_request_items', ['purchase_request_id'], unique=False)
    op.create_index(op.f('ix_purchase_request_items_tenant_id'), 'purchase_request_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_purchase_request_items_unit_of_measure_id'), 'purchase_request_items', ['unit_of_measure_id'], unique=False)
    op.create_table('receipt_prints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('is_reprint', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_prints_branch_id'), 'receipt_prints', ['branch_id'], unique=False)
    op.create_index(op.f('ix_receipt_prints_employee_id'), 'receipt_prints', ['employee_id'], unique=False)
    op.create_index(op.f('ix_receipt_prints_order_id'), 'receipt_prints', ['order_id'], unique=False)
    op.create_index(op.f('ix_receipt_prints_tenant_id'), 'receipt_prints', ['tenant_id'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_variant_id', 'ingredient_id', name='uq_recipe_items_variant_ingredient')
    )
    op.create_index(op.f('ix_recipe_items_ingredient_id'), 'recipe_items', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_product_variant_id'), 'recipe_items', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_tenant_id'), 'recipe_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_unit_of_measure_id'), 'recipe_items', ['unit_of_measure_id'], unique=False)
    op.create_table('variant_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('variant_group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('extra_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_group_id'], ['variant_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_options_tenant_id'), 'variant_options', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_variant_options_variant_group_id'), 'variant_options', ['variant_group_id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('whatsapp_conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_employee_id'), 'whatsapp_messages', ['employee_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_tenant_id'), 'whatsapp_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_whatsapp_conversation_id'), 'whatsapp_messages', ['whatsapp_conversation_id'], unique=False)
    op.create_table('cancellations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('requires_authorization', sa.Boolean(), nullable=False),
    sa.Column('requested_by_employee_id', sa.Uuid(), nullable=False),
    sa.Column('authorized_by_employee_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancellations_authorized_by_employee_id'), 'cancellations', ['authorized_by_employee_id'], unique=False)
    op.create_index(op.f('ix_cancellations_branch_id'), 'cancellations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cancellations_order_id'), 'cancellations', ['order_id'], unique=False)
    op.create_index(op.f('ix_cancellations_order_item_id'), 'cancellations', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_cancellations_requested_by_employee_id'), 'cancellations', ['requested_by_employee_id'], unique=False)
    op.create_index(op.f('ix_cancellations_tenant_id'), 'cancellations', ['tenant_id'], unique=False)
    op.create_table('order_item_addons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('addon_id', sa.Uuid(), nullable=False),
    sa.Column('applied_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_addons_addon_id'), 'order_item_addons', ['addon_id'], unique=False)
    op.create_index(op.f('ix_order_item_addons_order_item_id'), 'order_item_addons', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_item_addons_tenant_id'), 'order_item_addons', ['tenant_id'], unique=False)
    op.create_table('order_item_stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('kitchen_station_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kitchen_station_id'], ['kitchen_stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_stations_branch_id'), 'order_item_stations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_order_item_stations_kitchen_station_id'), 'order_item_stations', ['kitchen_station_id'], unique=False)
    op.create_index(op.f('ix_order_item_stations_order_item_id'), 'order_item_stations', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_item_stations_tenant_id'), 'order_item_stations', ['tenant_id'], unique=False)
    op.create_table('product_variant_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('variant_option_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_option_id'], ['variant_options.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_variant_id', 'variant_option_id', name='uq_product_variant_options_variant_option')
    )
    op.create_index(op.f('ix_product_variant_options_product_variant_id'), 'product_variant_options', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_product_variant_options_tenant_id'), 'product_variant_options', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_product_variant_options_variant_option_id'), 'product_variant_options', ['variant_option_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_ingredient_id'), 'purchase_order_items', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_tenant_id'), 'purchase_order_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_unit_of_measure_id'), 'purchase_order_items', ['unit_of_measure_id'], unique=False)
    op.create_table('purchase_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_payments_employee_id'), 'purchase_payments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_purchase_payments_purchase_order_id'), 'purchase_payments', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_payments_tenant_id'), 'purchase_payments', ['tenant_id'], unique=False)
    # Extend existing structural tables (negocio -> tenants, sucursal -> branches,
    # usuario alignment on users). Wrapped in batch_alter_table so the FK ADD
    # CONSTRAINT works on PostgreSQL (native ALTER) and SQLite (copy strategy).
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.create_index(batch_op.f('ix_branches_city_id'), ['city_id'], unique=False)
        batch_op.create_foreign_key('fk_branches_city_id', 'cities', ['city_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_tenants_city_id'), ['city_id'], unique=False)
        batch_op.create_foreign_key('fk_tenants_city_id', 'cities', ['city_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_person_id'), ['person_id'], unique=False)
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.create_foreign_key('fk_users_person_id', 'persons', ['person_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_person_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_person_id'))
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('username')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tenants_city_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tenants_city_id'))
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('city_id')
        batch_op.drop_column('tax_id')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_branches_city_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_branches_city_id'))
        batch_op.drop_column('is_primary')
        batch_op.drop_column('phone')
        batch_op.drop_column('city_id')
    op.drop_index(op.f('ix_purchase_payments_tenant_id'), table_name='purchase_payments')
    op.drop_index(op.f('ix_purchase_payments_purchase_order_id'), table_name='purchase_payments')
    op.drop_index(op.f('ix_purchase_payments_employee_id'), table_name='purchase_payments')
    op.drop_table('purchase_payments')
    op.drop_index(op.f('ix_purchase_order_items_unit_of_measure_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_tenant_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_ingredient_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_product_variant_options_variant_option_id'), table_name='product_variant_options')
    op.drop_index(op.f('ix_product_variant_options_tenant_id'), table_name='product_variant_options')
    op.drop_index(op.f('ix_product_variant_options_product_variant_id'), table_name='product_variant_options')
    op.drop_table('product_variant_options')
    op.drop_index(op.f('ix_order_item_stations_tenant_id'), table_name='order_item_stations')
    op.drop_index(op.f('ix_order_item_stations_order_item_id'), table_name='order_item_stations')
    op.drop_index(op.f('ix_order_item_stations_kitchen_station_id'), table_name='order_item_stations')
    op.drop_index(op.f('ix_order_item_stations_branch_id'), table_name='order_item_stations')
    op.drop_table('order_item_stations')
    op.drop_index(op.f('ix_order_item_addons_tenant_id'), table_name='order_item_addons')
    op.drop_index(op.f('ix_order_item_addons_order_item_id'), table_name='order_item_addons')
    op.drop_index(op.f('ix_order_item_addons_addon_id'), table_name='order_item_addons')
    op.drop_table('order_item_addons')
    op.drop_index(op.f('ix_cancellations_tenant_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_requested_by_employee_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_order_item_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_order_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_branch_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_authorized_by_employee_id'), table_name='cancellations')
    op.drop_table('cancellations')
    op.drop_index(op.f('ix_whatsapp_messages_whatsapp_conversation_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_tenant_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_employee_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_variant_options_variant_group_id'), table_name='variant_options')
    op.drop_index(op.f('ix_variant_options_tenant_id'), table_name='variant_options')
    op.drop_table('variant_options')
    op.drop_index(op.f('ix_recipe_items_unit_of_measure_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_tenant_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_product_variant_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_ingredient_id'), table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_receipt_prints_tenant_id'), table_name='receipt_prints')
    op.drop_index(op.f('ix_receipt_prints_order_id'), table_name='receipt_prints')
    op.drop_index(op.f('ix_receipt_prints_employee_id'), table_name='receipt_prints')
    op.drop_index(op.f('ix_receipt_prints_branch_id'), table_name='receipt_prints')
    op.drop_table('receipt_prints')
    op.drop_index(op.f('ix_purchase_request_items_unit_of_measure_id'), table_name='purchase_request_items')
    op.drop_index(op.f('ix_purchase_request_items_tenant_id'), table_name='purchase_request_items')
    op.drop_index(op.f('ix_purchase_request_items_purchase_request_id'), table_name='purchase_request_items')
    op.drop_index(op.f('ix_purchase_request_items_ingredient_id'), table_name='purchase_request_items')
    op.drop_table('purchase_request_items')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_purchase_request_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_branch_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_order_payments_tenant_id'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_order_id'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_employee_id'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_cash_session_id'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_branch_id'), table_name='order_payments')
    op.drop_table('order_payments')
    op.drop_index(op.f('ix_order_items_tenant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_branch_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_deliveries_tenant_id'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_order_id'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_delivery_run_id'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_delivery_route_id'), table_name='order_deliveries')
    op.drop_table('order_deliveries')
    op.drop_index(op.f('ix_customer_credit_payments_tenant_id'), table_name='customer_credit_payments')
    op.drop_index(op.f('ix_customer_credit_payments_employee_id'), table_name='customer_credit_payments')
    op.drop_index(op.f('ix_customer_credit_payments_customer_credit_id'), table_name='customer_credit_payments')
    op.drop_table('customer_credit_payments')
    op.drop_index(op.f('ix_cash_movements_tenant_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_cash_session_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_branch_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_attendances_tenant_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_planned_shift_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_employee_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_whatsapp_conversations_whatsapp_contact_id'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_tenant_id'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_employee_id'), table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    op.drop_index(op.f('ix_variant_groups_tenant_id'), table_name='variant_groups')
    op.drop_index(op.f('ix_variant_groups_product_id'), table_name='variant_groups')
    op.drop_table('variant_groups')
    op.drop_index(op.f('ix_purchase_requests_tenant_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_requested_by_employee_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_branch_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_approved_by_employee_id'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index(op.f('ix_product_variants_tenant_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_stations_tenant_id'), table_name='product_stations')
    op.drop_index(op.f('ix_product_stations_product_id'), table_name='product_stations')
    op.drop_index(op.f('ix_product_stations_kitchen_station_id'), table_name='product_stations')
    op.drop_table('product_stations')
    op.drop_index(op.f('ix_product_prices_tenant_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_branch_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_product_addons_tenant_id'), table_name='product_addons')
    op.drop_index(op.f('ix_product_addons_product_id'), table_name='product_addons')
    op.drop_index(op.f('ix_product_addons_addon_id'), table_name='product_addons')
    op.drop_table('product_addons')
    op.drop_index(op.f('ix_planned_shifts_tenant_id'), table_name='planned_shifts')
    op.drop_index(op.f('ix_planned_shifts_employee_id'), table_name='planned_shifts')
    op.drop_index(op.f('ix_planned_shifts_branch_id'), table_name='planned_shifts')
    op.drop_table('planned_shifts')
    op.drop_index(op.f('ix_orders_whatsapp_contact_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_employee_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_dining_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_branch_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_inventory_movements_tenant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_ingredient_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_employee_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_branch_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_category_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_employee_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_branch_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_delivery_runs_tenant_id'), table_name='delivery_runs')
    op.drop_index(op.f('ix_delivery_runs_employee_id'), table_name='delivery_runs')
    op.drop_index(op.f('ix_delivery_runs_delivery_route_id'), table_name='delivery_runs')
    op.drop_table('delivery_runs')
    op.drop_index(op.f('ix_delivery_route_drivers_tenant_id'), table_name='delivery_route_drivers')
    op.drop_index(op.f('ix_delivery_route_drivers_employee_id'), table_name='delivery_route_drivers')
    op.drop_index(op.f('ix_delivery_route_drivers_delivery_route_id'), table_name='delivery_route_drivers')
    op.drop_table('delivery_route_drivers')
    op.drop_index(op.f('ix_customer_preferences_tenant_id'), table_name='customer_preferences')
    op.drop_index('ix_customer_preferences_customer_key', table_name='customer_preferences')
    op.drop_index(op.f('ix_customer_preferences_customer_id'), table_name='customer_preferences')
    op.drop_table('customer_preferences')
    op.drop_index(op.f('ix_customer_credits_tenant_id'), table_name='customer_credits')
    op.drop_index(op.f('ix_customer_credits_customer_id'), table_name='customer_credits')
    op.drop_table('customer_credits')
    op.drop_index(op.f('ix_commissions_tenant_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_employee_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_cash_sessions_tenant_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_opened_by_employee_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_closed_by_employee_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_branch_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    op.drop_index(op.f('ix_supplier_ingredients_unit_of_measure_id'), table_name='supplier_ingredients')
    op.drop_index(op.f('ix_supplier_ingredients_tenant_id'), table_name='supplier_ingredients')
    op.drop_index(op.f('ix_supplier_ingredients_supplier_id'), table_name='supplier_ingredients')
    op.drop_index(op.f('ix_supplier_ingredients_ingredient_id'), table_name='supplier_ingredients')
    op.drop_table('supplier_ingredients')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_kitchen_stations_tenant_id'), table_name='kitchen_stations')
    op.drop_index(op.f('ix_kitchen_stations_branch_id'), table_name='kitchen_stations')
    op.drop_table('kitchen_stations')
    op.drop_index(op.f('ix_inventory_stocks_tenant_id'), table_name='inventory_stocks')
    op.drop_index(op.f('ix_inventory_stocks_ingredient_id'), table_name='inventory_stocks')
    op.drop_index(op.f('ix_inventory_stocks_branch_id'), table_name='inventory_stocks')
    op.drop_table('inventory_stocks')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_role_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_person_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_dining_tables_tenant_id'), table_name='dining_tables')
    op.drop_index(op.f('ix_dining_tables_branch_id'), table_name='dining_tables')
    op.drop_table('dining_tables')
    op.drop_index(op.f('ix_delivery_routes_tenant_id'), table_name='delivery_routes')
    op.drop_index(op.f('ix_delivery_routes_branch_id'), table_name='delivery_routes')
    op.drop_table('delivery_routes')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_person_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_whatsapp_contacts_tenant_id'), table_name='whatsapp_contacts')
    op.drop_table('whatsapp_contacts')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_ingredients_unit_of_measure_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_tenant_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_expense_categories_tenant_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_category_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_addons_tenant_id'), table_name='addons')
    op.drop_table('addons')
    op.drop_index(op.f('ix_persons_city_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('units_of_measure')
    op.drop_table('permissions')
    op.drop_table('countries')
    # ### end Alembic commands ###
